language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'

install:
  - pip install -U pip setuptools wheel
  - pip install -U pytest-cov codecov # for codecov.io integration
  - if [ "${TRAVIS_PYTHON_VERSION:0:3}" == "3.4" ]; then pip install readme_renderer==24.0; else  pip install -U readme_renderer; fi
  - python -c "import setuptools; print(setuptools.__version__)"

script:
  - TEST_WITH_INTERNET=1 python setup.py test
  - python setup.py check -r -s

after_success:
  - bash <(curl -s https://codecov.io/bash)
