name: Run doctest on Sphinx docs

on: [push, pull_request]

jobs:
  run-doctest:
    runs-on: ubuntu-latest
    name: doctest check
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run pytest with doctest args
        run: |
          pip3 install pytest 'websocket-client[docs]' rel
          pytest ./docs/source -v --doctest-glob="*.rst" --doctest-modules
